### ISSUE TITLE
Consider adding portobello to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [sophie-katz/portobello#10]
Hey @sophie-katz, Thanks for adopting SeaORM! 
It's our pleasure to see more inspirational projects were built on top of SeaORM :) 

Let us know if you have any [feature recommendation](https://github.com/SeaQL/sea-orm/issues/new/choose) or [feedback](https://github.com/SeaQL/sea-orm/discussions/new). Your contribution is what drive us forward! 

Some learning resources for you: [Documentation](https://www.sea-ql.org/SeaORM/), [Tutorial](https://www.sea-ql.org/sea-orm-tutorial/), [Cookbook](https://www.sea-ql.org/sea-orm-cookbook/), [Q&A](https://github.com/SeaQL/sea-orm/discussions) 
Join our [Discord server](https://discord.com/invite/uCPdDXzbdv) to chat with others in the SeaQL community! 

Feel free to submit a PR to showcase your project, https://github.com/SeaQL/sea-orm/issues/403.

**Comment by sophie-katz** [comment]
Hi @billy1624, thanks for reaching out!

After trying a few other Rust ORMs, SeaORM is definitely my favorite lol. It just makes writing the database layer simpler.

Portobello is just a hobby project for me and it's not even close to production-ready. It doesn't really use SeaORM too much yet, even though the database layer will be a lot larger later on. I'd be happy to have it in a showcase, but I don't know if you want this sort of project!
